import os

BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET")

DISCORD_WEBHOOK = os.getenv("DISCORD_WEBHOOK")
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")

COINS = [
    "BTC/USDT","ETH/USDT","BNB/USDT","XRP/USDT",
    "SOL/USDT","ADA/USDT","DOGE/USDT","AVAX/USDT",
    "DOT/USDT","MATIC/USDT","LTC/USDT","LINK/USDT",
    "ATOM/USDT","NEAR/USDT","APT/USDT","ARB/USDT",
    "OP/USDT","FIL/USDT","ETC/USDT","UNI/USDT",
    "AAVE/USDT","SUI/USDT","INJ/USDT","ICP/USDT",
    "GRT/USDT","SAND/USDT","MANA/USDT","AXS/USDT",
    "CHZ/USDT","FTM/USDT","RUNE/USDT","THETA/USDT",
    "ALGO/USDT","VET/USDT","XLM/USDT","EOS/USDT",
    "FLOW/USDT","IMX/USDT","1000SHIB/USDT","1000PEPE/USDT"
]

TIMEFRAMES = ["15m", "1h"]
